//Java Exception Handling (Try-catch)

import java.io.*;
import java.util.*;

public class Solution {

    public static void main(String[] args) {
        /* Enter your code here. Read input from STDIN. Print output to STDOUT. Your class should be named Solution. */
        Scanner scan = new Scanner(System.in);
       
    
        try{ 
        int x=scan.nextInt();
        int y=scan.nextInt();
            System.out.println(x/y);
        } catch (ArithmeticException e){
            System.out.println("java.lang.ArithmeticException: / by zero");
        }catch (InputMismatchException e){
            System.out.println("java.util.InputMismatchException");
        }
        
    }
}


-----------------------------------------------------



//Java Exception Handling

import java.util.Scanner;
class MyCalculator {
    /*
    * Create the method long power(int, int) here.
    */
    
     public long power(int n, int p) throws Exception{
         int sum = 1;
         
             if (n < 0 || p < 0){
                throw new Exception("n or p should not be negative.");
             } else if (n == 0 && p == 0){
                  throw new Exception("n and p should not be zero.");
             } else{
                 for (int i = 0; i < p; i++){
                     sum *= n;
                 }
             }

         return sum;
     }
    
}

public class Solution {
    public static final MyCalculator my_calculator = new MyCalculator();
    public static final Scanner in = new Scanner(System.in);
    
    public static void main(String[] args) {
        while (in .hasNextInt()) {
            int n = in .nextInt();
            int p = in .nextInt();
            
            try {
                System.out.println(my_calculator.power(n, p));
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }
}
